language: node_js
node_js:
  - '0.10'
  - '0.11'

notifications:
  email: false

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: HyV9nr8ZkdDyzaGtvRDTlejBl+mcauLw53iEw1RCrLKVafY9+2BVJbceAFp0cCAuDeHdYCvAu5pliRPuwnCqTK//wzXSR2p+nVbnyoFMS/MIzbo0BxqxMU05MJ46nF9L8gtuaNR5CRd0j8roIFu58janIDnh4xaidO5nZWHYN44=
  on:
    repo: tjwebb/sails-rigged
